// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_commerceAPI.Data;

#nullable disable

namespace e_commerceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509153014_AddIdentityAndWishlist")]
    partial class AddIdentityAndWishlist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("e_commerceAPI.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("e_commerceAPI.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("e_commerceAPI.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("e_commerceAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "men's clothing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "jewelery"
                        },
                        new
                        {
                            Id = 3,
                            Name = "electronics"
                        },
                        new
                        {
                            Id = 4,
                            Name = "women's clothing"
                        });
                });

            modelBuilder.Entity("e_commerceAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("e_commerceAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("e_commerceAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Your perfect pack for everyday use and walks in the forest.",
                            Image = "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png",
                            Price = 109.95m,
                            Rate = 3.8999999999999999,
                            RatingCount = 120,
                            Stock = 25,
                            Title = "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Slim-fitting style, contrast raglan long sleeve.",
                            Image = "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png",
                            Price = 22.3m,
                            Rate = 4.0999999999999996,
                            RatingCount = 259,
                            Stock = 40,
                            Title = "Mens Casual Premium Slim Fit T-Shirts"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Great outerwear jacket for seasonal use.",
                            Image = "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png",
                            Price = 55.99m,
                            Rate = 4.7000000000000002,
                            RatingCount = 500,
                            Stock = 18,
                            Title = "Mens Cotton Jacket"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Casual slim fit shirt.",
                            Image = "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png",
                            Price = 15.99m,
                            Rate = 2.1000000000000001,
                            RatingCount = 430,
                            Stock = 33,
                            Title = "Mens Casual Slim Fit"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Gold and silver dragon chain bracelet.",
                            Image = "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png",
                            Price = 695m,
                            Rate = 4.5999999999999996,
                            RatingCount = 400,
                            Stock = 10,
                            Title = "John Hardy Women's Bracelet"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Elegant jewelry piece.",
                            Image = "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png",
                            Price = 168m,
                            Rate = 3.8999999999999999,
                            RatingCount = 70,
                            Stock = 15,
                            Title = "Solid Gold Petite Micropave"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Engagement ring for women.",
                            Image = "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png",
                            Price = 9.99m,
                            Rate = 3.0,
                            RatingCount = 400,
                            Stock = 60,
                            Title = "White Gold Plated Princess Ring"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Stainless steel earrings.",
                            Image = "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_t.png",
                            Price = 10.99m,
                            Rate = 1.8999999999999999,
                            RatingCount = 100,
                            Stock = 55,
                            Title = "Rose Gold Plated Earrings"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "USB 3.0 portable hard drive.",
                            Image = "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png",
                            Price = 64m,
                            Rate = 3.2999999999999998,
                            RatingCount = 203,
                            Stock = 20,
                            Title = "WD 2TB External Hard Drive"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Fast SSD storage drive.",
                            Image = "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png",
                            Price = 109m,
                            Rate = 2.8999999999999999,
                            RatingCount = 470,
                            Stock = 12,
                            Title = "SanDisk SSD PLUS 1TB"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "High performance SSD.",
                            Image = "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png",
                            Price = 109m,
                            Rate = 4.7999999999999998,
                            RatingCount = 319,
                            Stock = 30,
                            Title = "Silicon Power 256GB SSD"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Gaming external drive.",
                            Image = "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png",
                            Price = 114m,
                            Rate = 4.7999999999999998,
                            RatingCount = 400,
                            Stock = 22,
                            Title = "WD 4TB Gaming Drive"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "IPS ultra-thin display.",
                            Image = "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png",
                            Price = 599m,
                            Rate = 2.8999999999999999,
                            RatingCount = 250,
                            Stock = 8,
                            Title = "Acer 21.5 Full HD Monitor"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Ultra wide curved monitor.",
                            Image = "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png",
                            Price = 999.99m,
                            Rate = 2.2000000000000002,
                            RatingCount = 140,
                            Stock = 5,
                            Title = "Samsung Curved Gaming Monitor"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Winter waterproof jacket.",
                            Image = "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png",
                            Price = 56.99m,
                            Rate = 2.6000000000000001,
                            RatingCount = 235,
                            Stock = 14,
                            Title = "Women's Snowboard Jacket"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Stylish biker jacket.",
                            Image = "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png",
                            Price = 29.95m,
                            Rate = 2.8999999999999999,
                            RatingCount = 340,
                            Stock = 27,
                            Title = "Women's Faux Leather Jacket"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "Lightweight raincoat.",
                            Image = "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png",
                            Price = 39.99m,
                            Rate = 3.7999999999999998,
                            RatingCount = 679,
                            Stock = 35,
                            Title = "Women's Rain Jacket"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Soft stretch top.",
                            Image = "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png",
                            Price = 9.85m,
                            Rate = 4.7000000000000002,
                            RatingCount = 130,
                            Stock = 50,
                            Title = "Women's Boat Neck T-Shirt"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Breathable sports shirt.",
                            Image = "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png",
                            Price = 7.95m,
                            Rate = 4.5,
                            RatingCount = 146,
                            Stock = 60,
                            Title = "Women's Moisture Shirt"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Casual cotton V-neck shirt.",
                            Image = "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_t.png",
                            Price = 12.99m,
                            Rate = 3.6000000000000001,
                            RatingCount = 145,
                            Stock = 45,
                            Title = "Women's Cotton T-Shirt"
                        });
                });

            modelBuilder.Entity("e_commerceAPI.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("e_commerceAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("e_commerceAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_commerceAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("e_commerceAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("e_commerceAPI.Models.CartItem", b =>
                {
                    b.HasOne("e_commerceAPI.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_commerceAPI.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("e_commerceAPI.Models.OrderItem", b =>
                {
                    b.HasOne("e_commerceAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_commerceAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("e_commerceAPI.Models.Product", b =>
                {
                    b.HasOne("e_commerceAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("e_commerceAPI.Models.WishlistItem", b =>
                {
                    b.HasOne("e_commerceAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_commerceAPI.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("e_commerceAPI.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("e_commerceAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("e_commerceAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("e_commerceAPI.Models.Product", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
